title: Files
modelClass: Jazz\Playground\Models\File
list: $/jazz/playground/models/file/columns.yaml
recordUrl: 'jazz/playground/files/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '20'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
