list: $/jazz/playground/models/file/columns.yaml
modelClass: Jazz\Playground\Models\File
title: File
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'jazz/playground/file/update/:id'
